Tentative Modif create Release

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -33,8 +33,12 @@ jobs:
 
     steps:
       - name: 'Print GITHUB_OUTPUT'
-        run: cat $GITHUB_OUTPUT
-
+        run: |
+          echo "GITHUB_OUTPUT contents:"
+          cat $GITHUB_OUTPUT
+          if [ $? -ne 0 ]; then
+          echo "Error reading GITHUB_OUTPUT"
+          fi
       - uses: 'actions/checkout@v3'
       - name: 'set variable for snapshot release'
         run: |
